import type { MetadataRoute } from 'next';
import { SITE_URL } from '@/lib/seo/config';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/$',
          '/de$',
          '/en$',
          '/de',
          '/en',
          '/de/',
          '/en/',
          '/de/templates',
          '/en/templates',
          '/de/agb',
          '/en/agb',
          '/de/datenschutz',
          '/en/datenschutz',
          '/de/widerruf',
          '/en/widerruf',
          '/de/impressum',
          '/en/impressum',
          '/favicon.svg',
          '/logo.svg',
          '/logo-icon.svg',
          '/og-image.png',
          '/opengraph-image',
          '/twitter-image',
        ],
        disallow: [
          '/api/',
          '/api/*',
          '/de/dashboard',
          '/de/dashboard/*',
          '/en/dashboard',
          '/en/dashboard/*',
          '/de/editor',
          '/de/editor/*',
          '/en/editor',
          '/en/editor/*',
          '/de/login',
          '/en/login',
          '/de/preview',
          '/de/preview/*',
          '/en/preview',
          '/en/preview/*',
          '/de/share',
          '/de/share/*',
          '/en/share',
          '/en/share/*',
          '/de/interview',
          '/de/interview/*',
          '/en/interview',
          '/en/interview/*',
          '/de/linkedin-photo',
          '/de/linkedin-photo/*',
          '/en/linkedin-photo',
          '/en/linkedin-photo/*',
        ],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
